### ISSUE TITLE
feature request: Human friendly time formatting strings

### ISSUE THREAD

**Issue by max-ishere** [BurntSushi/jiff#156]
I really need the better TZ support of `jiff`, but it doesn't have those nicer formatting strings `time` has. I prefer these readable ones because they're easier to write and read in the config file.

```toml
fmt = "[weekday repr:short], [month repr:short] [day] [year] [hour repr:12]:[minute]:[second] [period]"
fmt = "%a, %b %d %Y %I:%M:%S %p" # some C++ library that waybar uses
```

It doesn't really matter what format you go with, I just don't wanna guess that `%I` means 12h hour value.

Maybe it would make sense to move the parser to a separate crate, that way there can be a standard parser that can be shared across different time crates, and the time crates could just read the tokens and format accordingly.

One other feature I really want is to get the precision of the output, that way I can automatically set the sleep() duration without having to specify it in the config.
